### PR TITLE
Pagination added

### PR DESCRIPTION
**Pull request by lorenzo774**
Added pagination system with basic styling for the pagination component.

### CODE REVIEW

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Hey @lorenzo774, looks like there is a merge conflict in the code, can you have a look?

**Comment by lorenzo774** [comment]
Sorry, I didn't notice the new commit on main

**Comment by Dharmik48** [comment]
Alright, now it looks good to merge! Thanks a lot for your valuable contribution😄🚀

**Comment by lorenzo774** [comment]
No it's not, go back to the previous commit.

**Comment by lorenzo774** [comment]
Now I solved it

**Comment by Dharmik48** [comment]
> No it's not, go back to the previous commit.

Why? What happened?

**Comment by lorenzo774** [comment]
I did not merge search-feature and add-pagination

**Comment by lorenzo774** [comment]
Now I solved it locally but i can't push

**Comment by Dharmik48** [comment]
I reverted the merge, you should be able to push now👍🏻

**Comment by lorenzo774** [comment]
To revert-8-add-pagination from a new pull request?

**Comment by Dharmik48** [comment]
Yes, you will have to raise a new PR now.

**Comment by lorenzo774** [comment]
But I can't see my add-pagination branch

**Comment by Dharmik48** [comment]
Go to [this](https://github.com/lorenzo774/meme-generator/tree/add-pagination) page, it is there

**Pull request merged**
