### PR TITLE
Merge add pagination and search feature

### PR DESCRIPTION
**Pull request by lorenzo774**

### CODE REVIEW

**Comment by lorenzo774** [comment]
@Dharmik48  The branch has no conflicts but vercel had problems with deployment.

**Comment by Dharmik48** [comment]
Yeah because you are importing `./Pagination` in `Browse.js` but there is no such file

**Comment by lorenzo774** [comment]
Finally 😂

**Comment by Dharmik48** [comment]
Yeah! Finally we got it to work🚀

**Comment by Dharmik48** [comment]
Let's merge it! Thank you for the contribution😄

**Pull request merged**
