### PR TITLE
made search bar inline with header, and commented code

### PR DESCRIPTION
**Pull request by SethY8s**
Wanted to fix the styling on the search and make it inline with the header, also commented on the renderMemes variable since whoever is working on the page selector will need to modify the slice method depending on the page number.

### CODE REVIEW

**Comment by SethY8s** [comment]
Will fix this tomorrow!!!

**Comment by Dharmik48** [comment]
Hey @SethY8s, there seems to be a merge conflict in the PR, can you have a look so we can merge it?

**Comment by SethY8s** [comment]
Sorry @Dharmik48 !!! this is pretty much my first time doing open source and using git.

**Comment by Dharmik48** [comment]
> Sorry @Dharmik48 !!! this is pretty much my first time doing open source and using git.

No worries @SethY8s, you are doing great! Just tell me if you need help with anything👍🏻

**Comment by SethY8s** [comment]
Would you mind doing a zoom call or something? This is probably a pretty simple fix, but I just don't want to make it worse than it already is. If not I could just make a new fork and do it that way, since I think I'm already kinda messing things up haha.

**Comment by Dharmik48** [comment]
> Would you mind doing a zoom call or something? This is probably a pretty simple fix, but I just don't want to make it worse than it already is. If not I could just make a new fork and do it that way, since I think I'm already kinda messing things up haha.

A call is not possible but you can work on a new fork👍🏻

**Pull request closed without merging**
