### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by MahirMahdi**

### CODE REVIEW

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Why do the new screenshots have a white background when the actual site has a Turquoise-like color?

image

**Comment by MahirMahdi** [comment]
Screenshot (31)
I went to the live site and took a screenshot. The live site shows the background color white.

**Comment by Dharmik48** [comment]
> Screenshot (31) I went to the live site and took a screenshot. The live site shows the background color white.

Ya got it. It is because your system's theme is set to light that's why it is white.

**Comment by Dharmik48** [comment]
Let's merge this🚀

Thank you contributing😊

**Pull request merged**
