### PR TITLE
Remove horizontal scroll

### LINKED ISSUE #27: Horizontal Scrolling
When the site is opened, there is a horizontal scrollbar

### LINKED ISSUE #31: Add Issue templates
We want to add issue templates to [this repo](https://github.com/Dharmik48/notes-react-firebase-v2.0/tree/master/.github/ISSUE_TEMPLATE) similar to this repo

### PR DESCRIPTION
**Pull request by NehemiahDias**
this way there's no more scroll bar on the bottom, making the website prettier

### 🛠️ Fixes #Issue_Number

Closes #27 

### Related Issue/Addition to code
- Issue goes here

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Original | Updated
:----------------------:|:-----------:
** original screenshot  | ** updated screenshot **

### CODE REVIEW

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Hey @SWELLZ, we are using Tailwind CSS for the project, so can you fix the issue with Tailwind instead?

**Comment by NehemiahDias** [comment]
> Hey @SWELLZ, we are using Tailwind CSS for the project, so can you fix the issue with Tailwind instead?

Of course, my apologies it was late so it must've slipped my mind that there was tailwind haha.

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Hey @SWELLZ, it seems like the solution is not working. There still is a horizontal scroll bar

image

**Comment by NehemiahDias** [comment]
> Hey @SWELLZ, it seems like the solution is not working. There still is a horizontal scroll bar
> 
> image

Weird, It worked when I did it at first and now it's not haha, just put the tailwind class on the wrong component I suppose. It works now (hopefully it stays that way)

**Review by Dharmik48 — APPROVED** [review]
Great work🎉

The scroll bar is gone! Thanks a lot for contributing🚀

**Pull request merged**
