### PR TITLE
Created pull_request_template

### PR DESCRIPTION
**Pull request by harsh0c**
added PR template.

### CODE REVIEW

**Comment by harsh0c** [comment]
#19

**Review by KendallDoesCoding — COMMENTED** [review]
I suggest you make a template like this: https://github.com/KendallDoesCoding/mogul-christmas/blob/main/.github/pull_request_template.md as it looks better, in my opinion.

**Comment by harsh0c** [comment]
Thanks ! updated the template

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
> Thanks ! updated the template

welcome!

**Review by Dharmik48 — APPROVED** [review]
LGTM🚀

This looks great! Let's get it merged, Thanks a lot for your valuable contribution😄🚀

**Pull request merged**
