### PR TITLE
changes readme

### PR DESCRIPTION
**Pull request by kadeesterline**
I made a few changes to the readme:
1. added a little to the description
2. added installation steps
3. added screenshot examples
4. changed contribution

I didn't change any code, just added screenshot files and edited the readme. If theres anything you'd like me to change just let me know and I'll make the edit.

### CODE REVIEW

**Comment by Dharmik48** [comment]
Hey @kadeesterline thank you for the contribution! It looks great! 

Just a suggestion, I think the installation steps can be enhanced by moving forking and cloning in their own steps with code snippets and links. It would be great if you can change that.

Thank you :)

**Comment by kadeesterline** [comment]
Yeah no problem!

**Comment by kadeesterline** [comment]
I added more in depth steps to fork and clone.
- Forking now has a link to take you directly to a new fork
- Cloning now has code blocks and a link to explain the different ways to clone
- Npm install & start have been changed to code blocks to match
- Uncommented link to CONTRIBUTING.md

**Review by Dharmik48 — APPROVED** [review]
Looks good!🚀 Thanks a lot for contributing😄

**Pull request merged**
